### ISSUE TITLE
Boot Keyboard的问题

### ISSUE THREAD

**Issue by jerry-yuan** [yangzigy/yz_keyboard#1]
老兄用STM32 USB-FS的Joystick改的键盘,在BIOS下好使么....

**Comment by yangzigy** [comment]
我这个好使，键鼠一体，调工控板可以只插一个键盘

**Comment by jerry-yuan** [comment]
我看了一下我改的键盘和你的键盘，报告描述符是一样的，但是我的在部分BIOS下键位都是乱的，另外在Linux下似乎也存在问题。😂

**Comment by yangzigy** [comment]
只在BIOS乱吗？我这个之前调树莓派nanopi之类的板子没出过问题，x86的是uefi界面改Ubuntu，这几个场景都是一致的

**Comment by yangzigy** [comment]
只在BIOS乱吗？我这个之前调树莓派、nanopi之类的板子，x86的uefi界面改Ubuntu，这几个场景都是一致的
有时候是某个键一直按下，或者发送数据中有未初始化的位导致错乱

**Comment by jerry-yuan** [comment]
BIOS的话不是所有BIOS都键位乱,有些BIOS键位是乱的,有些BIOS就没事.

树莓派我没有尝试过是不是正常,x86的Ubuntu我试了几个了,有反应但是好像键盘布局全乱的.

至于某个键一直按下我的倒是没出现过....

**Comment by jerry-yuan** [comment]
已经修好了，发现报告描述符还是有点不一样的，在后边6字节的键码上的LOGICAL_MINIUM设置成了1，导致键码全部往后错了一个。

所以但凡读了报告描述符的BIOS(e.g.Dell 2015年以后的BIOS)或者操作系统(e.g.Linux)全部出问题了，而没有实际从设备中读取报告描述符直接照着Boot Keyboard的报告描述符读数据的BIOS(e.g.老BIOS)和操作系统(e.g.Windows)都是正常的。

感谢老兄提供的信息。
